import turtle

turtle.speed(3)

turtle.pencolor("blue")
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)

turtle.forward(100)
turtle.pencolor("blue")
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.back(80)

turtle.pencolor("red")
turtle.left(90)
turtle.forward(65)
turtle.right(90)
turtle.forward(65)
turtle.right(90)
turtle.forward(65)

turtle.mainloop()
