#import turtle

# turtle.speed(3)
#
# turtle.pencolor("blue")
# turtle.forward(100)
# turtle.left(90)
# turtle.forward(100)
# turtle.left(90)
# turtle.forward(100)
# turtle.left(90)
# turtle.forward(100)
# turtle.left(90)
#
# turtle.forward(100)
# turtle.pencolor("blue")
# turtle.forward(50)
# turtle.left(90)
# turtle.forward(50)
# turtle.left(90)
# turtle.forward(50)
# turtle.left(90)
# turtle.forward(50)
# turtle.left(90)
# turtle.back(80)
#
# turtle.pencolor("red")
# turtle.left(90)
# turtle.forward(65)
# turtle.right(90)
# turtle.forward(65)
# turtle.right(90)
# turtle.forward(65)
#
# turtle.mainloop()





HOMEWORK 



import turtle

turtle.speed(3)

turtle.pencolor("black")
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(120)
turtle.right(120)
turtle.forward(100)
turtle.left(120)
turtle.forward(70)
turtle.right(80)
turtle.forward(20)
turtle.right(100)
turtle.forward(150)
turtle.right(90)
turtle.forward(10)
turtle.circle(50)
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.forward(200)
turtle.right(90)
turtle.forward(5)
turtle.circle(50)
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.forward(50)
turtle.right(120)
turtle.forward(20)
turtle.right(60)
turtle.forward(20)
turtle.left(70)
turtle.forward(75)
turtle.right(70)
turtle.forward(150)
turtle.left(60)
turtle.forward(85)
turtle.right(60)
turtle.forward(37)
turtle.penup()
turtle.forward(30)
turtle.right(90)
turtle.forward(30)
turtle.pendown()
turtle.forward(50)
turtle.right(90)
turtle.forward(80)
turtle.right(120)
turtle.forward(60)
turtle.right(60)
turtle.forward(50)
turtle.mainloop()
